import "./CertificateModel"
import "./EventCertificateModel"
import "./ScanTemplate"
import "./EventParticipant"
import "./BlogPostModel"
import "./BlogInteractionModel"
import "./UserProfileModel"
import "./PrivacyAcceptanceModel"
import "./ProfileAuditModel"

// selective-processes (ADM)
import "../selective-processes/models/SelectionProcessModel"
import "../selective-processes/models/ExamModel"
import "../selective-processes/models/PricingTierModel"
import "../selective-processes/models/ApplicationModel"
import "../selective-processes/models/TicketModel"
