import "./CertificateModel"
import "./EventCertificateModel"
import "./ScanTemplate"
import "./EventParticipant"
import "./BlogPostModel"
import "./BlogInteractionModel"
import "./UserProfileModel"
import "./PrivacyAcceptanceModel"
import "./ProfileAuditModel"
// Continue importando os demais modelos...
